PROJECT_NAME=base

include ../../Makefile.os
include ../../Makefile.docker

docker_push:
	# Do nothing

docker_amend_manifest:
	# Do nothing

docker_push_manifest:
	# Do nothing

docker_sign_manifest:
	# Do nothing

docker_sbom:
	# Do nothing

docker_push_sbom:
	# Do nothing

docker_build : DOCKER_BUILD_ARGS := $(BASE_IMG_DOCKER_BUILD_ARGS)

.PHONY: build clean release